import {
  //men
  men1,
  men2,
  men3,
  men4,
  men5,
  men6,
  men7,
  men8,

  //women
  women1,
  women2,
  women3,
  women4,
  women5,
  women6,
  women7,
  women8,
  women9,
  women10,
  women11,
  women12,
  women13,
  women14,
  women15,
  women16,
  women17,

  //kids
  kid1,
  kid2,
  kid3,
  kid4,
  kid5,
  kid6,
  kid7,
  kid8,
  kid9,
  kid10,
  kid11,
} from "/public/images/index.js";

export const paginationItems = [
  {
    _id: "1",
    img: men1,
    productName: "Clothes",
    price: "35.00",
    color: "Yellow",
    brand: "Prada",
    des: "lore lore lore lorelorelore",
    cat: "Men",
  },
  {
    _id: "2",
    img: men2,
    productName: "clothes",
    price: "450",
    color: "Red",
    brand: "Goldstar",
    des: " gor goer djfaklsdfldsakfsa",
    cat: "Men",
  },

  {
    _id: "3",
    img: men3,
    productName: "clothes",
    price: "450",
    color: "Gray",
    brand: "Pantum",
    des: "sfdasjfldjalsjfdlakls",
    cat: "Men",
  },
  {
    _id: "4",
    img: men4,
    productName: "Clothes",
    price: "500",
    color: "Red",
    brand: "Zara",
    des: "dasfdahfsdhaks",
    cat: "Men",
  },
  {
    _id: "5",
    img: men5,
    productName: "CLothes",
    price: "450",
    color: "Blanc",
    brand: "Goldstar",
    des: "dasfdlakjfkdjsakld",
    cat: "Men",
  },
  {
    _id: "6",
    img: men6,
    productName: "CLothes",
    price: "450",
    color: "Blue",
    brand: "Zara",
    des: "asfdasfdasfd",
    cat: "Men",
  },
  {
    _id: "7",
    img: men7,
    productName: "Clothes",
    price: "450",
    color: "Blue",
    brand: "Gucci",
    des: "dfashfdhasfdlalhsj",
    cat: "Men",
  },
  {
    _id: "8",
    img: men8,
    productName: "CLothes",
    price: "25.00",
    color: "Blue",
    brand: "Goldstar",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Men",
  },
  {
    _id: "9",
    img: women1,
    productName: "Clothes",
    price: "220.00",
    color: "Gray",
    brand: "Gucci",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },
  {
    _id: "10",
    img: women2,
    productName: "Ruban",
    price: "25.00",
    color: "Gray",
    brand: "Zara",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },
  {
    _id: "11",
    img: women3,
    productName: "Clothes",
    price: "220.00",
    color: "Red",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
    brand: "Gucci",
  },
  {
    _id: "12",
    img: women4,
    productName: "Clothes",
    price: "25.00",
    color: "Yellow",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
    brand: "Zara",
  },
  {
    _id: "13",
    img: women5,
    productName: "Clothes",
    price: "220.00",
    color: "Red",
    brand: "Prada",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },

  {
    _id: "14",
    img: women6,
    productName: "Clothes",
    price: "25.00",
    color: "Blue",
    brand: "Prada",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },
  {
    _id: "15",
    img: women7,
    productName: "Clothes",
    price: "220.00",
    color: "Yellow",
    brand: "Gucci",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },
  {
    _id: "16",
    img: women8,
    productName: "Clothes",
    price: "25.00",
    color: "Green",
    brand: "Goldstar",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },
  {
    _id: "17",
    img: women9,
    productName: "Clothes",
    price: "220.00",
    color: "Green",
    brand: "Goldstar",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },

  {
    _id: "18",
    img: women10,
    productName: "Clothes",
    price: "25.00",
    color: "Green",
    brand: "Goldstar",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },
  {
    _id: "19",
    img: women11,
    productName: "CLothes",
    price: "220.00",
    color: "Yellow",
    brand: "Zara",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Women",
  },

  {
    _id: "20",
    img: women12,
    productName: "CLothes",
    price: "450",
    color: "Red",
    brand: "Zara",
    des: "safkldsafldja;s",
    cat: "Women",
  },

  {
    _id: "21",
    img: women13,
    productName: "Clothes",
    price: "450",
    color: "Green",
    brand: "Gucci",
    des: "asfdsahfdas",
    cat: "Women",
  },

  {
    _id: "22",
    img: women14,
    productName: "clothes",
    price: "450",
    color: "Green",
    brand: "Goldstar",
    des: "dsfklsafdas;kfka",
    cat: "Women",
  },

  {
    _id: "23",
    img: women15,
    productName: "Clothes",
    price: "450",
    color: "Green",
    brand: "Zara",
    des: "safdasfdafsa",
    cat: "Women",
  },

  {
    _id: "24",
    img: women16,
    productName: "Clothes",
    price: "450",
    color: "Yellow",
    brand: "Gucci",
    des: "asfdasfdsahfdlkjakljfdkljaskd",
    cat: "Women",
  },
  {
    _id: "25",
    img: women17,
    productName: "Clothes",
    price: "450",
    color: "Blanc",
    brand: "Gucci",
    des: "afsdfjklajslfkj;as",
    cat: "Women",
  },
  {
    _id: "26",
    img: kid1,
    productName: "Clothes",
    price: "450",
    color: "Green",
    brand: "Goldstar",
    des: "safdasfdkasklfd;lasfk",
    cat: "Kids",
  },
  {
    _id: "27",
    img: kid2,
    productName: "Clothes",
    price: "450",
    color: "Green",
    brand: "Prada",
    des: "sahfkdhaksfldas",
    cat: "Kids",
  },
  {
    _id: "28",
    img: kid3,
    productName: "Clothes",
    price: "450",
    color: "Yellow",
    brand: "Prada",
    des: "dasfdasda",
    cat: "Kids",
  },

  {
    _id: "29",
    img: kid4,
    productName: "Lcothes",
    price: "450",
    color: "Red",
    brand: "Gucci",
    des: "asfdasfdasfda",
    cat: "Kids",
  },
  {
    _id: "30",
    img: kid5,
    productName: "Clothes9",
    price: "450",
    color: "Red",
    brand: "Gucci",
    des: "dasfdsfdasfdasd",
    cat: "Kids",
  },
  {
    _id: "31",
    img: kid6,
    productName: "Clothes",
    price: "450",
    color: "Red",
    brand: "Gucci",
    des: "asafdahsfdajkls",
    cat: "Kids",
  },
  {
    _id: "32",
    img: kid7,
    productName: "CLothes",
    price: "450",
    color: "Gray",
    brand: "Gucci",
    des: "safdklasfdhasd",
    cat: "Kids",
  },
  {
    _id: "33",
    img: kid8,
    productName: "Cllothes9",
    price: "450",
    color: "Gray",
    brand: "Gucci",
    des: "Idsafdsafdasfdafasfdagdasc",
    cat: "Kids",
  },
  {
    _id: "34",
    img: kid9,
    productName: "Product",
    price: "450",
    color: "Red",
    brand: "Zara",
    des: "Idasfasfewqihfinv;akwe",
    cat: "Kids",
  },
  {
    _id: "35",
    img: kid10,
    productName: "Swaertere",
    price: "450",
    color: "Red",
    brand: "Gucci",
    des: "asfdsklamcm,nioqwjeofan",
    cat: "Kids",
  },
  {
    _id: "36",
    img: kid11,
    productName: "Clothes",
    price: "450",
    color: "Gray",
    brand: "Gucci",
    des: "dkasfdklsa;nceiowasds",
    cat: "Kids",
  },
];
